# ==============================================================================
# Merged Lakeflow Source: terna
# ==============================================================================
# This file is auto-generated by tools/scripts/merge_python_source.py
# Do not edit manually. Make changes to the source files instead.
# ==============================================================================

from abc import ABC, abstractmethod
from datetime import datetime, timedelta, timezone
from decimal import Decimal
from typing import Any, Iterator
import json
import time

from pyspark.sql import Row
from pyspark.sql.datasource import DataSource, DataSourceReader, SimpleDataSourceStreamReader
from pyspark.sql.types import *
import base64
import logging
import requests
import uuid


def register_lakeflow_source(spark):
    """Register the Lakeflow Python source with Spark."""

    ########################################################
    # src/databricks/labs/community_connector/libs/utils.py
    ########################################################

    def _parse_struct(value: Any, field_type: StructType) -> Row:
        """Parse a dictionary into a PySpark Row based on StructType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for StructType, got {type(value)}")
        # Spark Python -> Arrow conversion require missing StructType fields to be assigned None.
        if value == {}:
            raise ValueError(
                "field in StructType cannot be an empty dict. "
                "Please assign None as the default value instead."
            )
        field_dict = {}
        for field in field_type.fields:
            if field.name in value:
                field_dict[field.name] = parse_value(value.get(field.name), field.dataType)
            elif field.nullable:
                field_dict[field.name] = None
            else:
                raise ValueError(f"Field {field.name} is not nullable but not found in the input")
        return Row(**field_dict)


    def _parse_array(value: Any, field_type: ArrayType) -> list:
        """Parse a list into a PySpark array based on ArrayType schema."""
        if not isinstance(value, list):
            if field_type.containsNull:
                return [parse_value(value, field_type.elementType)]
            raise ValueError(f"Expected a list for ArrayType, got {type(value)}")
        return [parse_value(v, field_type.elementType) for v in value]


    def _parse_map(value: Any, field_type: MapType) -> dict:
        """Parse a dictionary into a PySpark map based on MapType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for MapType, got {type(value)}")
        return {
            parse_value(k, field_type.keyType): parse_value(v, field_type.valueType)
            for k, v in value.items()
        }


    def _parse_string(value: Any) -> str:
        """Convert value to string."""
        return str(value)


    def _parse_integer(value: Any) -> int:
        """Convert value to integer."""
        if isinstance(value, str) and value.strip():
            return int(float(value)) if "." in value else int(value)
        if isinstance(value, (int, float)):
            return int(value)
        raise ValueError(f"Cannot convert {value} to integer")


    def _parse_float(value: Any) -> float:
        """Convert value to float."""
        return float(value)


    def _parse_decimal(value: Any) -> Decimal:
        """Convert value to Decimal."""
        return Decimal(value) if isinstance(value, str) and value.strip() else Decimal(str(value))


    def _parse_boolean(value: Any) -> bool:
        """Convert value to boolean."""
        if isinstance(value, str):
            lowered = value.lower()
            if lowered in ("true", "t", "yes", "y", "1"):
                return True
            if lowered in ("false", "f", "no", "n", "0"):
                return False
        return bool(value)


    def _parse_date(value: Any) -> datetime.date:
        """Convert value to date."""
        if isinstance(value, str):
            for fmt in ("%Y-%m-%d", "%m/%d/%Y", "%d-%m-%Y", "%Y/%m/%d"):
                try:
                    return datetime.strptime(value, fmt).date()
                except ValueError:
                    continue
            return datetime.fromisoformat(value).date()
        if isinstance(value, datetime):
            return value.date()
        raise ValueError(f"Cannot convert {value} to date")


    def _parse_timestamp(value: Any) -> datetime:
        """Convert value to timestamp."""
        if isinstance(value, str):
            ts_value = value.replace("Z", "+00:00") if value.endswith("Z") else value
            try:
                return datetime.fromisoformat(ts_value)
            except ValueError:
                for fmt in ("%Y-%m-%d %H:%M:%S", "%Y/%m/%d %H:%M:%S"):
                    try:
                        return datetime.strptime(ts_value, fmt)
                    except ValueError:
                        continue
        elif isinstance(value, (int, float)):
            return datetime.fromtimestamp(value)
        elif isinstance(value, datetime):
            return value
        raise ValueError(f"Cannot convert {value} to timestamp")


    def _decode_string_to_bytes(value: str) -> bytes:
        """Try to decode a string as base64, then hex, then UTF-8."""
        try:
            return base64.b64decode(value)
        except Exception:
            pass
        try:
            return bytes.fromhex(value)
        except Exception:
            pass
        return value.encode("utf-8")


    def _parse_binary(value: Any) -> bytes:
        """Convert value to bytes. Tries base64, then hex, then UTF-8 for strings."""
        if isinstance(value, bytes):
            return value
        if isinstance(value, bytearray):
            return bytes(value)
        if isinstance(value, str):
            return _decode_string_to_bytes(value)
        if isinstance(value, list):
            return bytes(value)
        return str(value).encode("utf-8")


    # Mapping of primitive types to their parser functions
    _PRIMITIVE_PARSERS = {
        StringType: _parse_string,
        IntegerType: _parse_integer,
        LongType: _parse_integer,
        FloatType: _parse_float,
        DoubleType: _parse_float,
        DecimalType: _parse_decimal,
        BooleanType: _parse_boolean,
        DateType: _parse_date,
        TimestampType: _parse_timestamp,
        BinaryType: _parse_binary,
    }


    def parse_value(value: Any, field_type: DataType) -> Any:
        """
        Converts a JSON value into a PySpark-compatible data type based on the provided field type.
        """
        if value is None:
            return None

        # Handle complex types
        if isinstance(field_type, StructType):
            return _parse_struct(value, field_type)
        if isinstance(field_type, ArrayType):
            return _parse_array(value, field_type)
        if isinstance(field_type, MapType):
            return _parse_map(value, field_type)

        # Handle primitive types via type-based lookup
        try:
            field_type_class = type(field_type)
            if field_type_class in _PRIMITIVE_PARSERS:
                return _PRIMITIVE_PARSERS[field_type_class](value)

            # Check for custom UDT handling
            if hasattr(field_type, "fromJson"):
                return field_type.fromJson(value)

            raise TypeError(f"Unsupported field type: {field_type}")
        except (ValueError, TypeError) as e:
            raise ValueError(f"Error converting '{value}' ({type(value)}) to {field_type}: {str(e)}")


    ########################################################
    # src/databricks/labs/community_connector/interface/lakeflow_connect.py
    ########################################################

    class LakeflowConnect(ABC):
        """Base interface that each source connector must implement.

        Subclass this and implement all abstract methods to create a connector that
        integrates with the community connector library and ingestion pipeline.
        """

        def __init__(self, options: dict[str, str]) -> None:
            """
            Initialize the source connector with parameters needed to connect to the source.
            Args:
                options: A dictionary of parameters like authentication tokens, table names,
                    and other configurations.
            """
            self.options = options

        @abstractmethod
        def list_tables(self) -> list[str]:
            """
            List names of all the tables supported by the source connector.
            The list could either be a static list or retrieved from the source via API.
            Returns:
                A list of table names.
            """

        @abstractmethod
        def get_table_schema(
            self, table_name: str, table_options: dict[str, str]
        ) -> StructType:
            """
            Fetch the schema of a table.
            Args:
                table_name: The name of the table to fetch the schema for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the schema.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A StructType object representing the schema of the table.
            """

        @abstractmethod
        def read_table_metadata(
            self, table_name: str, table_options: dict[str, str]
        ) -> dict:
            """
            Fetch the metadata of a table.
            Args:
                table_name: The name of the table to fetch the metadata for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the metadata.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A dictionary containing the metadata of the table. It should include the
                following keys:
                    - primary_keys: List of string names of the primary key columns of
                        the table.
                    - cursor_field: The name of the field to use as a cursor for
                        incremental loading.
                    - ingestion_type: The type of ingestion to use for the table. It
                        should be one of the following values:
                        - "snapshot": For snapshot loading.
                        - "cdc": Capture incremental changes (no delete support).
                        - "cdc_with_deletes": Capture incremental changes with delete
                            support. Requires implementing read_table_deletes().
                        - "append": Incremental append.
            """

        @abstractmethod
        def read_table(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read the records of a table and return an iterator of records and an offset.

            The framework calls this method repeatedly to paginate through data.
            start_offset is None only on the very first call of the very first run
            of a connector. On subsequent runs the framework resumes from the last
            checkpointed offset, so start_offset will already be populated. Each
            call returns (records, end_offset). The framework passes end_offset as
            start_offset to the next call. Pagination stops when the returned
            offset equals start_offset (i.e., no more data).

            For tables that cannot be incrementally read, return None as the offset to
            read the entire table in one batch. Non-checkpointable synthetic offsets can
            be used to split the data into multiple batches.

            Args:
                table_name: The name of the table to read.
                start_offset: The offset to start reading from. None only on the
                    first call of the first run; on subsequent runs it carries the
                    checkpointed offset from the previous run.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to read the table.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of records as JSON-compatible dicts. Do NOT convert
                    values according to get_table_schema(); the framework handles that.
                offset: A dict representing the position after this batch.
            """

        def read_table_deletes(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read deleted records from a table for CDC delete synchronization.
            This method is called when ingestion_type is "cdc_with_deletes" to fetch
            records that have been deleted from the source system.

            This method follows the same pagination and offset protocol as read_table:
            the framework calls it repeatedly, passing the previous end_offset as
            start_offset, until the returned offset equals start_offset.

            Override this method if any of your tables use ingestion_type
            "cdc_with_deletes". The default implementation raises NotImplementedError.

            The returned records should have at minimum the primary key fields and
            cursor field populated. Other fields can be null.

            Args:
                table_name: The name of the table to read deleted records from.
                start_offset: The offset to start reading from (same format as read_table).
                table_options: A dictionary of options for accessing the table.
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of deleted records (must include primary keys and cursor).
                offset: A dict (same format as read_table).
            """
            raise NotImplementedError(
                "read_table_deletes() must be implemented when ingestion_type is 'cdc_with_deletes'"
            )


    ########################################################
    # src/databricks/labs/community_connector/sources/terna/terna_schemas.py
    ########################################################

    SUPPORTED_TABLES = [
        "total_load",
        "actual_generation",
        "renewable_generation",
        "physical_foreign_flow",
    ]

    # =============================================================================
    # Table schema definitions (API returns strings for numeric fields)
    # =============================================================================

    # total_load: date, date_tz, date_offset, total_load_MW, forecast_total_load_MW, bidding_zone
    TOTAL_LOAD_SCHEMA = StructType(
        [
            StructField("date", StringType(), True),
            StructField("date_tz", StringType(), True),
            StructField("date_offset", StringType(), True),
            StructField("total_load_MW", StringType(), True),
            StructField("forecast_total_load_MW", StringType(), True),
            StructField("bidding_zone", StringType(), True),
        ]
    )

    # Bidding zones supported by the Terna API
    TOTAL_LOAD_BIDDING_ZONES = [
        "North",
        "Centre-North",
        "South",
        "Centre-South",
        "Sardinia",
        "Sicily",
        "Calabria",
        "Italy",
    ]

    # actual_generation: date, date_tz, date_offset, actual_generation_GWh, primary_source
    ACTUAL_GENERATION_SCHEMA = StructType(
        [
            StructField("date", StringType(), True),
            StructField("date_tz", StringType(), True),
            StructField("date_offset", StringType(), True),
            StructField("actual_generation_GWh", StringType(), True),
            StructField("primary_source", StringType(), True),
        ]
    )

    # renewable_generation: date, date_tz, date_offset, renewable_generation_GWh, energy_source
    RENEWABLE_GENERATION_SCHEMA = StructType(
        [
            StructField("date", StringType(), True),
            StructField("date_tz", StringType(), True),
            StructField("date_offset", StringType(), True),
            StructField("renewable_generation_GWh", StringType(), True),
            StructField("energy_source", StringType(), True),
        ]
    )

    # physical_foreign_flow: date, date_tz, date_offset, country, import, export, physical_foreign_flow_MW
    # "import" is a Python keyword; API field is "import" -> we use "import_" in schema or keep "import" as string key
    PHYSICAL_FOREIGN_FLOW_SCHEMA = StructType(
        [
            StructField("date", StringType(), True),
            StructField("date_tz", StringType(), True),
            StructField("date_offset", StringType(), True),
            StructField("country", StringType(), True),
            StructField("import", StringType(), True),
            StructField("export", StringType(), True),
            StructField("physical_foreign_flow_MW", StringType(), True),
        ]
    )

    TABLE_SCHEMAS = {
        "total_load": TOTAL_LOAD_SCHEMA,
        "actual_generation": ACTUAL_GENERATION_SCHEMA,
        "renewable_generation": RENEWABLE_GENERATION_SCHEMA,
        "physical_foreign_flow": PHYSICAL_FOREIGN_FLOW_SCHEMA,
    }

    # =============================================================================
    # Table metadata: primary keys, cursor field, ingestion type (all append)
    # =============================================================================

    TABLE_METADATA = {
        "total_load": {
            "primary_keys": ["date", "bidding_zone"],
            "cursor_field": "date",
            "ingestion_type": "append",
        },
        "actual_generation": {
            "primary_keys": ["date", "primary_source"],
            "cursor_field": "date",
            "ingestion_type": "append",
        },
        "renewable_generation": {
            "primary_keys": ["date", "energy_source"],
            "cursor_field": "date",
            "ingestion_type": "append",
        },
        "physical_foreign_flow": {
            "primary_keys": ["date", "country"],
            "cursor_field": "date",
            "ingestion_type": "append",
        },
    }


    ########################################################
    # src/databricks/labs/community_connector/sources/terna/terna.py
    ########################################################

    logger = logging.getLogger(__name__)

    # Token endpoint path (relative to base_url)
    TOKEN_PATH = "/public-api/access-token"
    # Default base URL for data and (if applicable) transmission APIs
    DEFAULT_BASE_URL = "https://api.terna.it"
    # Token refresh margin: refresh if expiry is within this many seconds
    TOKEN_REFRESH_MARGIN_SEC = 60
    # Retries for transient errors (403 with "Over Qps" is Terna rate limit)
    MAX_RETRIES = 5
    INITIAL_BACKOFF = 1.0
    RETRIABLE_STATUS_CODES = {429, 500, 502, 503}
    # Backoff when 403 "Developer Over Qps" (longer to respect rate limit)
    QPS_BACKOFF_SEC = 3.0
    # Terna API allows at most this many days per request; longer ranges are chunked
    TERNA_MAX_DAYS_PER_REQUEST = 60
    # Terna API allows history only within the last N solar years (date_from not sooner than 01/01/(year-N))
    TERNA_MAX_HISTORY_SOLAR_YEARS = 5

    class TernaLakeflowConnect(LakeflowConnect):
        """LakeflowConnect implementation for the Terna Public API."""

        def __init__(self, options: dict[str, str]) -> None:
            """
            Initialize the Terna connector.

            Expected options:
                - client_id: OAuth 2.0 Client Credentials application key (required).
                - client_secret: OAuth 2.0 Client Credentials secret (required).
                - base_url: Base URL for the API (default https://api.terna.it).
                - x_api_key: Optional API key for Physical Foreign Flow when that
                  endpoint uses x-api-key instead of Bearer token.
            """
            super().__init__(options)

            client_id = options.get("client_id")
            client_secret = options.get("client_secret")

            if not client_id or not client_secret:
                raise ValueError(
                    "Terna connector requires 'client_id' and 'client_secret' in options"
                )

            self._client_id = client_id
            self._client_secret = client_secret
            self._base_url = (options.get("base_url") or DEFAULT_BASE_URL).rstrip("/")

            self._oauth_token: str | None = None
            self._oauth_expires_at: float = 0.0
            self._session = requests.Session()
            self._session.headers["Accept"] = "application/json"


        def list_tables(self) -> list[str]:
            """List names of all tables supported by this connector."""
            return SUPPORTED_TABLES

        def get_table_schema(
            self, table_name: str, table_options: dict[str, str]
        ) -> StructType:
            """Return the Spark schema for the given table."""
            self._validate_table(table_name)
            return TABLE_SCHEMAS[table_name]

        def read_table_metadata(
            self, table_name: str, table_options: dict[str, str]
        ) -> dict:
            """Return metadata (primary_keys, cursor_field, ingestion_type) for the table."""
            self._validate_table(table_name)
            return dict(TABLE_METADATA[table_name])

        def read_table(
            self,
            table_name: str,
            start_offset: dict | None,
            table_options: dict[str, str],
        ) -> tuple[Iterator[dict], dict]:
            """Read records by date-range chunks; cursor is the last 'date' value (yyyy-mm-dd hh:mm:ss)."""
            self._validate_table(table_name)
            reader = {
                "total_load": self._read_total_load,
                #"actual_generation": self._read_actual_generation,
                #"renewable_generation": self._read_renewable_generation,
                #"physical_foreign_flow": self._read_physical_foreign_flow,
            }[table_name]
            return reader(start_offset, table_options)

        def _get_token(self) -> str:
            """Obtain or refresh OAuth 2.0 access token (Client Credentials). Retries on 403/429 (rate limit)."""
            now = time.time()
            if self._oauth_token and now < self._oauth_expires_at - TOKEN_REFRESH_MARGIN_SEC:
                return self._oauth_token

            url = f"{self._base_url}{TOKEN_PATH}"
            data = {
                "grant_type": "client_credentials",
                "client_id": self._client_id,
                "client_secret": self._client_secret,
            }
            backoff = QPS_BACKOFF_SEC
            last_error = None
            for attempt in range(MAX_RETRIES):
                resp = self._session.post(
                    url,
                    data=data,
                    headers={"Content-Type": "application/x-www-form-urlencoded"},
                    timeout=30,
                )
                if resp.status_code == 200:
                    body = resp.json()
                    self._oauth_token = body.get("access_token")
                    if not self._oauth_token:
                        raise RuntimeError("Terna token response missing access_token")
                    expires_in = int(body.get("expire_format_api_dates_in", 300))
                    self._oauth_expires_at = now + expires_in
                    return self._oauth_token
                last_error = RuntimeError(
                    f"Terna token request failed: {resp.status_code} {resp.text}"
                )
                if resp.status_code in (403, 429) and attempt < MAX_RETRIES - 1:
                    time.sleep(backoff)
                    backoff *= 2
                    continue
                raise last_error
            raise last_error

        def _request(
            self,
            method: str,
            path: str,
            params: dict[str, str] | None = None,
        ) -> requests.Response:
            """Issue an API request with Bearer or x-api-key auth; retry on 429/5xx and 403 Over Qps."""
            params = params or {}
            url = f"{self._base_url}{path}"

            self._session.headers["Authorization"] = f"Bearer {self._get_token()}"
            self._session.headers["businessID"] = str(uuid.uuid4())

            backoff = INITIAL_BACKOFF
            for attempt in range(MAX_RETRIES):
                resp = self._session.request(method, url, params=params, timeout=60)
                is_retriable = resp.status_code in RETRIABLE_STATUS_CODES or (
                    resp.status_code == 403 and "qps" in (resp.text or "").lower()
                )
                if not is_retriable:
                    return resp
                if attempt < MAX_RETRIES - 1:
                    delay = QPS_BACKOFF_SEC if (resp.status_code == 403) else backoff
                    time.sleep(delay)
                    backoff *= 2
            return resp

        def _validate_table(self, table_name: str) -> None:
            if table_name not in SUPPORTED_TABLES:
                raise ValueError(
                    f"Table {table_name!r} is not supported. "
                    f"Supported tables: {SUPPORTED_TABLES}"
                )

        # -------------------------------------------------------------------------
        # Date-range helpers (API uses dd/mm/yyyy; cursor is yyyy-mm-dd hh:mm:ss)
        # -------------------------------------------------------------------------

        @staticmethod
        def _format_api_date(dt: datetime) -> str:
            """Format datetime as dd/mm/yyyy for API query params."""
            return dt.strftime("%d/%m/%Y")

        @staticmethod
        def _string_to_datetime(date_string: str) -> datetime:
            """Format datetime as dd/mm/yyyy for API query params."""
            return datetime.strptime(date_string, "%d/%m/%Y").replace(tzinfo=timezone.utc)

        @staticmethod
        def _format_cursor(dt: datetime) -> str:
            """Format datetime for cursor/range_end (yyyy-mm-dd hh:mm:ss)."""
            return dt.strftime("%d/%m/%Y")

        def _read_table_chunk(
            self,
            table_name: str,
            path: str,
            date_from: datetime,
            date_to: datetime,
            table_options: dict[str, str],
            array_key: str,
            extra_params: dict[str, str] | None = None,
        ) -> list[dict]:
            """Request one date chunk and return the data array; empty list on error or no data."""

            logger.info(f"Querying data for api {table_name} from: {date_from}, to {date_to}")

            if date_from == date_to:
                return []

            params = {
                "dateFrom": self._format_api_date(date_from),
                "dateTo": self._format_api_date(date_to),
            }
            if extra_params:
                params.update(extra_params)

            logger.debug(f"Querying data for api {table_name} with params: {params}")

            resp = self._request("GET", path, params=params)
            if resp.status_code != 200:
                raise RuntimeError(
                    f"Terna API error for {table_name}: {resp.status_code} {resp.text}"
                )
            body = resp.json()
            data = body.get(array_key)

            if not isinstance(data, list):
                return []

            return data

        def _read_total_load(
            self,
            start_offset: dict | None,
            table_options: dict[str, str],
        ) -> tuple[Iterator[dict], dict]:
            """Read total_load in one date chunk. Optional table_options: biddingZone (comma or repeated)."""

            extra = {}
            bidding_zone = (
                table_options.get("biddingZone")
                or table_options.get("bidding_zone")
                or table_options.get("biddingzone")
            )
            if bidding_zone:
                # API accepts multiple biddingZone params
                if bidding_zone not in TOTAL_LOAD_BIDDING_ZONES:
                    raise ValueError(
                        f"Terna connector: Invalid biddingZone value {bidding_zone}. Must be one of: {', '.join(TOTAL_LOAD_BIDDING_ZONES)}"
                    )
                extra["biddingZone"] = bidding_zone.strip()

            date_from = (
                table_options.get("date_from")
                or table_options.get("dateFrom")
                or table_options.get("datefrom")
            )

            date_to = (
                table_options.get("date_to")
                or table_options.get("dateTo")
                or table_options.get("dateto")
            )

            if date_from is None:
                raise ValueError(
                    "Terna connector, API total_load requires 'date_from'"
                )

            date_from = self._string_to_datetime(date_from)
            now = datetime.now(timezone.utc)
            min_allowed = datetime(
                now.year - TERNA_MAX_HISTORY_SOLAR_YEARS, 1, 1, tzinfo=timezone.utc
            )
            if date_from < min_allowed:
                raise ValueError(
                    f"Terna connector: 'date_from' must be within the last {TERNA_MAX_HISTORY_SOLAR_YEARS} solar years, not sooner than 01/01/{now.year - TERNA_MAX_HISTORY_SOLAR_YEARS}"
                )

            if date_to is not None:
                date_to = self._string_to_datetime(date_to)
            else:
                date_to = datetime.now(timezone.utc)

            if self._format_cursor(date_from) == self._format_cursor(date_to):
                return iter([]), {'cursor': self._format_cursor(date_to)}

            if start_offset is None or start_offset.get("cursor") is None:
                # We are in a full refresh. Normally I want all data from date_from to date_to unless date_to is None
                pass       
            else:
                # We are in CDC. date_from is the cursor from the previous run. Normally I want all data from date_from to date_to unless date_to is None
                date_from = self._string_to_datetime(start_offset.get("cursor"))

                if date_to is None:
                    # We are in the setup where I want all data from date_from to current time
                    pass

            chunks = []
            current_start = date_from
            while current_start < date_to:
                current_end = min(current_start + timedelta(days=TERNA_MAX_DAYS_PER_REQUEST - 1), date_to)
                chunks.append((current_start, current_end))
                current_start = current_end + timedelta(days=1)

            if len(chunks) > 1:
                logger.info(f"Requested more than 60 days, will be split in {len(chunks)} API calls.")
            else:
                chunks.append((date_from, date_to))

            records = []
            for chunk in chunks:
                date_from, date_to = chunk
                records.extend(self._read_table_chunk(
                    "total_load",
                    "/load/v2.0/total-load",
                    date_from,
                    date_to,
                    table_options,
                    "total_load",
                    extra_params=extra if extra else None,
                ))

            return iter(records), {'cursor': self._format_cursor(chunks[-1][1])}
    '''
        def _read_actual_generation(
            self,
            start_offset: dict | None,
            table_options: dict[str, str],
        ) -> tuple[Iterator[dict], dict]:
            """Read actual_generation in one date chunk. Optional table_options: type (primary source)."""
            chunk_result, range_end_opt = self._next_chunk(start_offset, table_options)
            if chunk_result is None:
                return iter([]), start_offset or {}

            from_date, to_date = chunk_result
            extra = {}
            type_opt = table_options.get("type")
            if type_opt:
                extra["type"] = type_opt.strip()

            records = self._read_table_chunk(
                "actual_generation",
                "/generation/v2.0/actual-generation",
                from_date,
                to_date,
                table_options,
                "actual_generation",
                extra_params=extra if extra else None,
            )
            if not records:
                end_offset = {"cursor": self._format_cursor(to_date)}
            else:
                max_date = self._max_date_in_records(records)
                end_offset = {"cursor": max_date} if max_date else dict(start_offset or {})
            if range_end_opt is not None:
                end_offset["range_end"] = range_end_opt
            elif start_offset and "range_end" in start_offset:
                end_offset["range_end"] = start_offset["range_end"]
            return iter(records), end_offset

        def _read_renewable_generation(
            self,
            start_offset: dict | None,
            table_options: dict[str, str],
        ) -> tuple[Iterator[dict], dict]:
            """Read renewable_generation in one date chunk. Optional table_options: type."""
            chunk_result, range_end_opt = self._next_chunk(start_offset, table_options)
            if chunk_result is None:
                return iter([]), start_offset or {}

            from_date, to_date = chunk_result
            extra = {}
            type_opt = table_options.get("type")
            if type_opt:
                extra["type"] = type_opt.strip()

            records = self._read_table_chunk(
                "renewable_generation",
                "/generation/v2.0/renewable-generation",
                from_date,
                to_date,
                table_options,
                "renewable_generation",
                extra_params=extra if extra else None,
            )
            if not records:
                end_offset = {"cursor": self._format_cursor(to_date)}
            else:
                max_date = self._max_date_in_records(records)
                end_offset = {"cursor": max_date} if max_date else dict(start_offset or {})
            if range_end_opt is not None:
                end_offset["range_end"] = range_end_opt
            elif start_offset and "range_end" in start_offset:
                end_offset["range_end"] = start_offset["range_end"]
            return iter(records), end_offset

        def _read_physical_foreign_flow(
            self,
            start_offset: dict | None,
            table_options: dict[str, str],
        ) -> tuple[Iterator[dict], dict]:
            """Read physical_foreign_flow in one date chunk."""
            chunk_result, range_end_opt = self._next_chunk(start_offset, table_options)
            if chunk_result is None:
                return iter([]), start_offset or {}

            from_date, to_date = chunk_result
            records = self._read_table_chunk(
                "physical_foreign_flow",
                "/transmission/v2.0/physical-foreign-flow",
                from_date,
                to_date,
                table_options,
                "physical_foreign_flow"
            )
            if not records:
                end_offset = {"cursor": self._format_cursor(to_date)}
            else:
                max_date = self._max_date_in_records(records)
                end_offset = {"cursor": max_date} if max_date else dict(start_offset or {})
            if range_end_opt is not None:
                end_offset["range_end"] = range_end_opt
            elif start_offset and "range_end" in start_offset:
                end_offset["range_end"] = start_offset["range_end"]
            return iter(records), end_offset
    '''


    ########################################################
    # src/databricks/labs/community_connector/sparkpds/lakeflow_datasource.py
    ########################################################

    LakeflowConnectImpl = TernaLakeflowConnect
    # Constant option or column names
    METADATA_TABLE = "_lakeflow_metadata"
    TABLE_NAME = "tableName"
    TABLE_NAME_LIST = "tableNameList"
    TABLE_CONFIGS = "tableConfigs"
    IS_DELETE_FLOW = "isDeleteFlow"


    class LakeflowStreamReader(SimpleDataSourceStreamReader):
        """
        Implements a data source stream reader for Lakeflow Connect.
        Currently, only the simpleStreamReader is implemented, which uses a
        more generic protocol suitable for most data sources that support
        incremental loading.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.lakeflow_connect = lakeflow_connect
            self.schema = schema

        def initialOffset(self):
            return {}

        def read(self, start: dict) -> (Iterator[tuple], dict):
            is_delete_flow = self.options.get(IS_DELETE_FLOW) == "true"
            # Strip delete flow options before passing to connector
            table_options = {
                k: v for k, v in self.options.items() if k != IS_DELETE_FLOW
            }

            if is_delete_flow:
                records, offset = self.lakeflow_connect.read_table_deletes(
                    self.options[TABLE_NAME], start, table_options
                )
            else:
                records, offset = self.lakeflow_connect.read_table(
                    self.options[TABLE_NAME], start, table_options
                )
            rows = map(lambda x: parse_value(x, self.schema), records)
            return rows, offset

        def readBetweenOffsets(self, start: dict, end: dict) -> Iterator[tuple]:
            # TODO: This does not ensure the records returned are identical across repeated calls.
            # For append-only tables, the data source must guarantee that reading from the same
            # start offset will always yield the same set of records.
            # For tables ingested as incremental CDC, it is only necessary that no new changes
            # are missed in the returned records.
            return self.read(start)[0]


    class LakeflowBatchReader(DataSourceReader):
        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]

        def read(self, partition):
            all_records = []
            if self.table_name == METADATA_TABLE:
                all_records = self._read_table_metadata()
            else:
                all_records, _ = self.lakeflow_connect.read_table(
                    self.table_name, None, self.options
                )

            rows = map(lambda x: parse_value(x, self.schema), all_records)
            return iter(rows)

        def _read_table_metadata(self):
            table_name_list = self.options.get(TABLE_NAME_LIST, "")
            table_names = [o.strip() for o in table_name_list.split(",") if o.strip()]
            all_records = []
            table_configs = json.loads(self.options.get(TABLE_CONFIGS, "{}"))
            for table in table_names:
                metadata = self.lakeflow_connect.read_table_metadata(
                    table, table_configs.get(table, {})
                )
                all_records.append({TABLE_NAME: table, **metadata})
            return all_records


    class LakeflowSource(DataSource):
        """
        PySpark DataSource implementation for Lakeflow Connect.
        """

        def __init__(self, options):
            self.options = options
            # TEMPORARY: LakeflowConnectImpl is replaced with the actual implementation
            # class during merge. See the placeholder comment at the top of this file.
            self.lakeflow_connect = LakeflowConnectImpl(options)  # pylint: disable=abstract-class-instantiated

        @classmethod
        def name(cls):
            return "lakeflow_connect"

        def schema(self):
            table = self.options[TABLE_NAME]
            if table == METADATA_TABLE:
                return StructType(
                    [
                        StructField(TABLE_NAME, StringType(), False),
                        StructField("primary_keys", ArrayType(StringType()), True),
                        StructField("cursor_field", StringType(), True),
                        StructField("ingestion_type", StringType(), True),
                    ]
                )
            else:
                return self.lakeflow_connect.get_table_schema(table, self.options)

        def reader(self, schema: StructType):
            return LakeflowBatchReader(self.options, schema, self.lakeflow_connect)

        def simpleStreamReader(self, schema: StructType):
            return LakeflowStreamReader(self.options, schema, self.lakeflow_connect)


    spark.dataSource.register(LakeflowSource)
